# Site settings
title: christacaggiano
email: christacaggiano@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Personal website of Christa Caggiano
baseurl:  # the subpath of your site, e.g. /blog
url: "https://christacaggiano.github.io" # the base hostname & protocol for your site
twitter_username: christacaggiano
github_username:  christacaggiano

# Build settings
markdown: kramdown
permalink: pretty
