# Site settings
url: "https://christacaggiano.github.io/about" # the base hostname & protocol for your site
twitter_username: christacaggiano
github_username:  christacaggiano

# Build settings
markdown: kramdown
permalink: pretty
