# Site settings
title: "christa"
email: christacaggiano@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  christacaggiano &copy 2017
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://f-word.co" # the base hostname & protocol for your site
twitter_username: christacaggiano
github_username:  christacaggiano

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: rouge

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "blog/page/:num/"

# Minification
sass:
  style: compressed
