# Site settings
url: "https://www.christa.science/" # the base hostname & protocol for your site
twitter_username: christacaggiano
github_username:  christacaggiano
email: christacaggiano@gmail.com

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

future: true
