# Site settings
url: "https://christacaggiano.github.io" # the base hostname & protocol for your site
twitter_username: christacaggiano
github_username:  christacaggiano

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
