# Site settings
title: christacaggiano
email: christacaggiano@gmail.com
description: Personal website of Christa Caggiano
url: "https://christacaggiano.github.io" # the base hostname & protocol for your site
twitter_username: christacaggiano
github_username:  christacaggiano

# Build settings
markdown: kramdown
permalink: pretty
